unstable_features = true
indent_style = "Visual"
comment_width = 100
max_width = 100

binop_separator = "Back"
brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"
enum_discrim_align_threshold = 20
force_multiline_blocks = true
format_strings = true
space_after_colon = true
space_before_colon = true
struct_field_align_threshold = 20

